### PR TITLE
Update tailwind & fix typo

### PR DESCRIPTION
**Pull request by quick007**

### CODE REVIEW

**Comment by grahac** [comment]
Would love for this to get submitted to support Tailwind 3.0!

**Comment by quick007** [comment]
I'm honestly not sure how to add JIT, so it's marked as a draft.

**Comment by Ak4zh** [comment]
It works already if you --force install.
So I assume this pull request is safe to move out of draft.

**Comment by quick007** [comment]
> It works already if you --force install. So I assume this pull request is safe to move out of draft.

The author said they want nightwind as a JIT extension as well

**Pull request closed without merging**
